language: node_js
node_js:
- '8.15'
branches:
  only:
  - master
  - www
before_install: npm i -g firebase-tools
install:
- cd functions
- npm install
script: 
- npm test
- npm run deploy -- --token $FIREBASE_TOKEN